// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83LBRPQuMabzHsn2Mtucs9Y9xTeqzEJ0',
    appId: '1:700062154047:web:e538dfb97ceeeb190b678a',
    databaseURL: 'https://mastermind-1a14c-default-rtdb.firebaseio.com',
    messagingSenderId: '700062154047',
    projectId: 'mastermind-1a14c',
    authDomain: 'mastermind-1a14c.firebaseapp.com',
    storageBucket: 'mastermind-1a14c.firebasestorage.app',
    measurementId: 'G-B7PQC9LYJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIIhiXdBlzKkUNKvXrFobWj6SIbCAHacE',
    appId: '1:700062154047:android:396ef688238388b40b678a',
    messagingSenderId: '700062154047',
    projectId: 'mastermind-1a14c',
    storageBucket: 'mastermind-1a14c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8GWX23PHuzNdYDGkvAS9LNd_h6VcEk8',
    appId: '1:700062154047:ios:f9ebd6d06e3eda060b678a',
    messagingSenderId: '700062154047',
    projectId: 'mastermind-1a14c',
    storageBucket: 'mastermind-1a14c.firebasestorage.app',
    iosBundleId: 'com.example.medconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR8GWX23PHuzNdYDGkvAS9LNd_h6VcEk8',
    appId: '1:700062154047:ios:f9ebd6d06e3eda060b678a',
    messagingSenderId: '700062154047',
    projectId: 'mastermind-1a14c',
    storageBucket: 'mastermind-1a14c.firebasestorage.app',
    iosBundleId: 'com.example.medconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB83LBRPQuMabzHsn2Mtucs9Y9xTeqzEJ0',
    appId: '1:700062154047:web:2d7946f34cc5adb20b678a',
    messagingSenderId: '700062154047',
    projectId: 'mastermind-1a14c',
    authDomain: 'mastermind-1a14c.firebaseapp.com',
    storageBucket: 'mastermind-1a14c.firebasestorage.app',
    measurementId: 'G-TP7SHNH2JF',
  );
}
